# Домашняя работа - Матрицы

[Учебник](http://judge.mipt.ru/tasks/book/Butuzov-VF-Krutitskaya-NCh-Shishkin-AA-Lineinaya-algebra-v-voprosah-i-zadachah.pdf) - Бутузов, Крутиницкая, Шишкин

In [69]:
import numpy as np
from numpy.linalg import inv, det, solve, matrix_rank

## Задача 1 (стр 10, упр. 1)

Даны матрицы А и В.

$$ A = \begin{bmatrix}
-1 & 2 \\
0 & 1 \\
-3 & 0
\end{bmatrix}, B =  \begin{bmatrix}
0 & 1 \\
1/2 & -1/2 \\
-1 & 4
\end{bmatrix}$$

Найти:
* вариант 1: $A+B$
* вариант 2: $A-B$
* вариант 3: $A-4B$
* вариант 4: $3A+2B$
* вариант 5: $3A-4B$

* вариант 6: подобрать такие х и y, чтобы все элементы матрицы $xA+yB$ были равны 0.

In [37]:
A = np.array([[-1, 2], [0, 1], [-3, 0]])
B = np.array([[0, 1], [1/2, -1/2], [-1, 4]])
A, B

(array([[-1,  2],
        [ 0,  1],
        [-3,  0]]),
 array([[ 0. ,  1. ],
        [ 0.5, -0.5],
        [-1. ,  4. ]]))

In [38]:
print('Вариант 1: A+B')
print(A + B)

Вариант 1: A+B
[[-1.   3. ]
 [ 0.5  0.5]
 [-4.   4. ]]


In [39]:
print('Вариант 2: A-B')
print(A - B)

Вариант 2: A-B
[[-1.   1. ]
 [-0.5  1.5]
 [-2.  -4. ]]


In [40]:
print('Вариант 3: A-4*B')
print(A-4*B)

Вариант 3: A-4*B
[[ -1.  -2.]
 [ -2.   3.]
 [  1. -16.]]


In [41]:
print('Вариант 4: 3A+2B')
print(3*A + 2*B)

Вариант 4: 3A+2B
[[ -3.   8.]
 [  1.   2.]
 [-11.   8.]]


In [42]:
print('Вариант 5: 3A-4B')
print(3*A - 4*B)

Вариант 5: 3A-4B
[[ -3.   2.]
 [ -2.   5.]
 [ -5. -16.]]


Написать все ответы компактно в LaTeX.

# Задача 2 (стр 10, упр 3)

Даны матрицы А и В.

$$ A = \begin{bmatrix}
3 & 1 & -2 \\
1 & 3 & 0
\end{bmatrix}, B =  \begin{bmatrix}
0 & 2 & 4 \\
1 & -1 & 0 \end{bmatrix}$$

Найти:
* вариант 1: $A^T$
* вариант 2: $B^T$
* вариант 3: $A^T + B^T$
* вариант 4: $2A^T+B^T$
* вариант 5: $3A^T-2B^T$

In [43]:
A = np.array([[3, 1, -2],[1, 3, 0]])
B = np.array([[0, 2, 4],[1, -1, 0]])
A, B

(array([[ 3,  1, -2],
        [ 1,  3,  0]]),
 array([[ 0,  2,  4],
        [ 1, -1,  0]]))

In [44]:
print('Вариант 1: AT')
A.T

Вариант 1: AT


array([[ 3,  1],
       [ 1,  3],
       [-2,  0]])

In [45]:
print('Вариант 2: BT')
B.T

Вариант 2: BT


array([[ 0,  1],
       [ 2, -1],
       [ 4,  0]])

In [46]:
print('Вариант 3: AT + BT')
A.T + B.T

Вариант 3: AT + BT


array([[3, 2],
       [3, 2],
       [2, 0]])

In [47]:
print('Вариант 4: 2AT+BT')
2*A.T + B.T

Вариант 4: 2AT+BT


array([[6, 3],
       [4, 5],
       [0, 0]])

In [48]:
print('Вариант 5: 3AT - 2BT')
3*A.T - 2*B.T

Вариант 5: 3AT - 2BT


array([[  9,   1],
       [ -1,  11],
       [-14,   0]])

# Задача 3 (стр 11, упр 5 а) - всем вариантам

Даны матрицы А и В.

$$ A = \begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix}, B =  \begin{bmatrix}
0 & 0 \\
1 & 0 \end{bmatrix}$$

Найти:
* $AB$
* $BA$
* $A^{T}B^T$
* $B^{T}A^T$

In [49]:
A = np.array([[0, 1], [1, 0]])
B = np.array([[0, 0], [1, 0]])
A, B

(array([[0, 1],
        [1, 0]]),
 array([[0, 0],
        [1, 0]]))

In [50]:
A.dot(B)

array([[1, 0],
       [0, 0]])

In [51]:
B.dot(A)

array([[0, 0],
       [0, 1]])

In [52]:
A.T.dot(B.T)

array([[0, 0],
       [0, 1]])

## Задача 4 (стр 11, упр 5 б, г, д)

### Вариант 1 и 2
Даны матрицы А и В.

$$ A = \begin{bmatrix}
1 & -3 \\
2 & 1
\end{bmatrix}, B =  \begin{bmatrix}
0 & -1 \\
1 & 0 \end{bmatrix}$$

Найти:
* 1 вариант: $AB$ и $B^{T}A^T$
* 2 вариант: $BA$ и $A^{T}B^T$

In [53]:
A = np.array([[1, -3], [2, 1]])
B = np.array([[0, -1], [1, 0]])
A, B

(array([[ 1, -3],
        [ 2,  1]]),
 array([[ 0, -1],
        [ 1,  0]]))

In [54]:
print('Вариант 1')
print('AB = \n', A.dot(B))
print('BTAT = \n', B.T.dot(A.T))

Вариант 1
AB = 
 [[-3 -1]
 [ 1 -2]]
BTAT = 
 [[-3  1]
 [-1 -2]]


In [55]:
print('Вариант 2')
print('BA = \n', B.dot(A))
print('ATBT = \n', A.T.dot(B.T))

Вариант 2
BA = 
 [[-2 -1]
 [ 1 -3]]
ATBT = 
 [[-2  1]
 [-1 -3]]


### Вариант 3 и 4
Даны матрицы А и В.

$$ A = \begin{bmatrix}
1 & 0 & -1\\
2 & 3 & -2
\end{bmatrix}, B =  \begin{bmatrix}
1 & 2 \\
1 & 0 \\
3 & 1\end{bmatrix}$$

Найти:
* 3 вариант: $AB$ и $B^{T}A^T$
* 4 вариант: $BA$ и $A^{T}B^T$

In [56]:
A = np.array([[1, 0, -1], [2, 3, 2]])
B = np.array([[1, 2],[1, 0], [3,1]])
A, B

(array([[ 1,  0, -1],
        [ 2,  3,  2]]),
 array([[1, 2],
        [1, 0],
        [3, 1]]))

In [57]:
print('Вариант 3')
print('AB = \n', A.dot(B))
print('BTAT = \n', B.T.dot(A.T))

Вариант 3
AB = 
 [[-2  1]
 [11  6]]
BTAT = 
 [[-2 11]
 [ 1  6]]


In [58]:
print('Вариант 4')
print('BA = \n', B.dot(A))
print('ATBT = \n', A.T.dot(B.T))

Вариант 4
BA = 
 [[ 5  6  3]
 [ 1  0 -1]
 [ 5  3 -1]]
ATBT = 
 [[ 5  1  5]
 [ 6  0  3]
 [ 3 -1 -1]]


### Вариант 5 и 6
Даны матрицы А и В.

$$ A = \begin{bmatrix}
0 & -5 & 1 & 0 \\
3 & 0 & -2 & 0 \\
1 & 1 & 0 & 0
\end{bmatrix}, B =  \begin{bmatrix}
1 & -1 & 0 \\
1 & 0 & 0 \\
1 & -1 & 0 \\
1 & 0 & 0
\end{bmatrix}$$

Найти:
* 5 вариант: $AB$ и $B^{T}A^T$
* 6 вариант: $BA$ и $A^{T}B^T$

In [59]:
A = np.array([[0, -5, 1, 0], [3, 0, -2, 0], [1, 1, 0, 0]])
B = np.array([[1, -1, 0], [1, 0, 0], [1, -1, 0], [1, 0, 0]])
A, B

(array([[ 0, -5,  1,  0],
        [ 3,  0, -2,  0],
        [ 1,  1,  0,  0]]),
 array([[ 1, -1,  0],
        [ 1,  0,  0],
        [ 1, -1,  0],
        [ 1,  0,  0]]))

In [60]:
print('Вариант 5')
print('AB = \n', A.dot(B))
print('BTAT = \n', B.T.dot(A.T))

Вариант 5
AB = 
 [[-4 -1  0]
 [ 1 -1  0]
 [ 2 -1  0]]
BTAT = 
 [[-4  1  2]
 [-1 -1 -1]
 [ 0  0  0]]


In [61]:
print('Вариант 6')
print('BA = \n', B.dot(A))
print('ATBT = \n', A.T.dot(B.T))

Вариант 6
BA = 
 [[-3 -5  3  0]
 [ 0 -5  1  0]
 [-3 -5  3  0]
 [ 0 -5  1  0]]
ATBT = 
 [[-3  0 -3  0]
 [-5 -5 -5 -5]
 [ 3  1  3  1]
 [ 0  0  0  0]]


# Задача 5 (стр 11, упр 9 + стр 21, упр 17)

А1 - вариант 1, А2 - вариант 2 и так далее. Найти:
* Обратную матрицу
* размер матрицы
* ранг матрицы

$ \begin{gather} A1 = 
\begin{bmatrix}
1 & 2 \\
2 & 5
\end{bmatrix}
\end{gather}$

$ \begin{gather} A2 = 
\begin{bmatrix}
-1 & 4 \\
8 & 0
\end{bmatrix}
\end{gather}$

$ \begin{gather} A3 = 
\begin{bmatrix}
1 & 1 \\
2 & 3
\end{bmatrix}
\end{gather}$

$ \begin{gather} A4 = 
\begin{bmatrix}
1 & 3 & -5 \\
0 & 1 & 2 \\
0 & 0 & 1
\end{bmatrix}
\end{gather}$

$ \begin{gather} A5 = 
\begin{bmatrix}
2 & 2 & 3 \\
1 & -1 & 0 \\
-1 & 2 & 1
\end{bmatrix}
\end{gather}$

$ \begin{gather} A6 = 
\begin{bmatrix}
1 & 3 \\
1 & 4
\end{bmatrix}
\end{gather}$


In [66]:
A1 = np.array([[1, 2],[2, 5]])
A2 = np.array([[-1, 4],[8, 0]])
A3 = np.array([[1, 1],[2, 3]])
A4 = np.array([[1, 3, -5],[0, 1, 2], [0, 0, 1]])
A5 = np.array([[2, 2, 3],[1, -1, 0], [-1, 2, 1]])
A6 = np.array([[1, 3],[1, 4]])

In [70]:
ALIST = [A1, A2, A3, A4, A5, A6]
for i, M in enumerate(ALIST):
    print(f'Вариант А{i+1}')
    print(M)
    print(inv(M))
    print(f'size={M.shape} rank={matrix_rank(M)}')

Вариант А1
[[1 2]
 [2 5]]
[[ 5. -2.]
 [-2.  1.]]
size=(2, 2) rank=2
Вариант А2
[[-1  4]
 [ 8  0]]
[[0.      0.125  ]
 [0.25    0.03125]]
size=(2, 2) rank=2
Вариант А3
[[1 1]
 [2 3]]
[[ 3. -1.]
 [-2.  1.]]
size=(2, 2) rank=2
Вариант А4
[[ 1  3 -5]
 [ 0  1  2]
 [ 0  0  1]]
[[ 1. -3. 11.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]
size=(3, 3) rank=3
Вариант А5
[[ 2  2  3]
 [ 1 -1  0]
 [-1  2  1]]
[[ 1. -4. -3.]
 [ 1. -5. -3.]
 [-1.  6.  4.]]
size=(3, 3) rank=3
Вариант А6
[[1 3]
 [1 4]]
[[ 4. -3.]
 [-1.  1.]]
size=(2, 2) rank=2


## Задача 6. Найти Х (упр 8 и упр 19)

TODO: добавить 19 а, б, в

E1) 
$\begin{gather}
\begin{bmatrix}
1 & 2 \\
3 & 5
\end{bmatrix} \cdot X = 
\begin{bmatrix}
4 & -6 \\
2 & 1
\end{bmatrix}
\end{gather}$

E2) 
$\begin{gather} X \cdot
\begin{bmatrix}
1 & 1 & -1 \\
2 & 1 & 0 \\
1 & -1 & 1
\end{bmatrix} = 
\begin{bmatrix}
1 & -1 & 3 \\
4 & 3 & 2 \\
1 & -2 & 5
\end{bmatrix}
\end{gather}$

E3) 
$\begin{gather}
\begin{bmatrix}
2 & 1 \\
3 & 2
\end{bmatrix} \cdot X \cdot 
\begin{bmatrix}
-3 & 2\\
5 & -3
\end{bmatrix}
= 
\begin{bmatrix}
-2 & 4 \\
3 & -1
\end{bmatrix}
\end{gather}$

E4) 
$\begin{gather}
\begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix} \cdot X \cdot 
\begin{bmatrix}
5 & 2\\
0 & 6
\end{bmatrix}
= 
\begin{bmatrix}
0 & 0 \\
0 & 1
\end{bmatrix}
\end{gather}$

E5) 
$\begin{gather}
\begin{bmatrix}
-1 & 0 \\
1 & -1
\end{bmatrix} \cdot X \cdot 
\begin{bmatrix}
-1 & 0 \\
1 & -1
\end{bmatrix}
= 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\end{gather}$

In [75]:
print('Задача 5.1: AX=B')
A = np.array([[1, 2],[3, 5]])
B = np.array([[4, -6],[2, 1]])
X = inv(A).dot(B)
print(X)
print(np.allclose(np.dot(A, X), B))

Задача 5.1: AX=B
[[-16.  32.]
 [ 10. -19.]]
True


In [76]:
print('Задача 5.2: XA=B')
A = np.array([[1, 1, -1],[2, 1, 0], [1, -1, 1]])
B = np.array([[1, -1, 3], [4, 3, 2],[1, -2, 5]])
X = B.dot(inv(A))
print(X)
print(np.allclose(np.dot(X, A), B))

Задача 5.2: XA=B
[[-3.00000000e+00  2.00000000e+00  2.22044605e-16]
 [-4.00000000e+00  5.00000000e+00 -2.00000000e+00]
 [-5.00000000e+00  3.00000000e+00  4.44089210e-16]]
True


In [80]:
print('Задача 5.3: AXB=C')
A = np.array([[2, 1],[3, 2]])
B = np.array([[-3, 2],[5, -3]])
C = np.array([[-2, 4],[3, -1]])
X = inv(A).dot(C).dot(inv(B))
print(X)
print(np.allclose(A.dot(X).dot(B), C))

Задача 5.3: AXB=C
[[ 24.  13.]
 [-34. -18.]]
True


In [81]:
print('Задача 5.4: AXB=C')
A = np.array([[0, 1],[1, 0]])
B = np.array([[5, 2],[0, 6]])
C = np.array([[0, 0],[0, 1]])
X = inv(A).dot(C).dot(inv(B))
print(X)
print(np.allclose(A.dot(X).dot(B), C))

Задача 5.4: AXB=C
[[0.         0.16666667]
 [0.         0.        ]]
True


In [82]:
print('Задача 5.5: AXA=B')
A = np.array([[-1, 0],[1, -1]])
B = np.array([[1, 2],[3, 4]])
X = inv(A).dot(B).dot(inv(A))
print(X)
print(np.allclose(A.dot(X).dot(A), B))

Задача 5.5: AXA=B
[[ 3.  2.]
 [10.  6.]]
True
